### ISSUE TITLE
CFBundleVersion missing in xcframework files

### ISSUE THREAD

**Issue by ethan021021** [kean/Pulse#11]
In Pulse / PulseUI it seems the frameworks are missing a CFBundleVersion in the Info.plist for the frameworks. Would you mind adding values in there? Looks like I can't submit my app to AppStore Connect without them having a CFBundleVersion.

**Comment by kean** [comment]
Fixed in https://github.com/kean/PulseUI/releases/tag/0.14.2

![Screen Shot 2021-04-12 at 15 43 23](https://user-images.githubusercontent.com/1567433/114452043-fb1fb380-9ba5-11eb-8ed1-2331854320cc.png)

There is an issue with swift-create-xcframework where they don't add `CFBundleVersion` by default https://github.com/unsignedapps/swift-create-xcframework/issues/37. I haven't encountered it with my apps because I was building from source.

**Comment by ethan021021** [comment]
Thanks a ton for adding that so quickly! Appreciate it

**Comment by finnsch** [comment]
The same problem occurs in the latest version 0.15.0. I reverted back to 0.14.2 for now.

**Comment by jojost1** [comment]
Same for me, it's back in 0.15.0.

**Comment by kean** [comment]
Fixed in https://github.com/kean/Pulse/releases/tag/0.15.1. I need to add more automation.
