### ISSUE TITLE
Google Map does not load for 3.0.0 and above

### ISSUE THREAD

**Issue by kushal211** [kean/Pulse#155]
When I used version 3.0.0 and above it does not load Google Maps.

After investigation, I found that it is the issue with the latest release when you directly use 

`URLSessionProxyDelegate.enableAutomaticRegistration()`

The quick solution is to use version less than 3.0.0

**Comment by vovander** [comment]
I have the same issue

**Comment by kean** [comment]
Hi, nothing significant changed in `URLSessionProxyDelegate` in Pulse 3, so I'm not sure what might be the root cause. What OS version have you tested on? Is there anything in the logs/stacktraces that indicates what the issue might be?

The only change in `URLSessionProxyDelegate` was removing conditional compilation from:

![Screenshot 2023-02-05 at 10 02 41 AM](https://user-images.githubusercontent.com/1567433/216827160-6dd74cbe-31b4-4614-8562-608060ec6d3b.png)

Can you please try removing this code entirely from the file and see if that works?

**Comment by kushal211** [comment]
@kean  - Thanks for the feedback.

Yes, I was surprised too when I found out this was causing the issue. I have tested in iOS 16.1, 16.2, and 16.3.

I removed `URLSessionProxyDelegate` integration and manually integrated using `EventMonitor` protocol and it's working perfectly.

Also, I did not find anything in the `logs/stacktraces` for this issue.

**Comment by ayuzhin** [comment]
Hello @kean. I confirm, GTMSessionFetcher https://cocoapods.org/pods/GoogleAPIClientForREST breaks when using URLSessionProxyDelegate.enableAutomaticRegistration(). GTMSessionFetcher is used in all google services such as maps, disk, etc.

**Comment by kean** [comment]
Potentially related: https://github.com/kean/Pulse/issues/141

**Comment by kean** [comment]
`GTMSessionFetcher` has a lot of code that manages session creation and delegate. Does someone have a sample project where you could integrate Pulse and debug it?

P.S. I wish there was a simple way to observe `URLSession` without intercepting its delegate.

**Comment by ayuzhin** [comment]
As requested, I provide a test case based on reading Google Drive. 
https://github.com/ayuzhin/google-drive-demo.git

There are two buttons on the main screen:
1. Read items from Google Drive
1. Display Pulse console

If you don't use the `URLSession` global design by using `URLSessionProxyDelegate` via `URLSessionProxyDelegate.enableAutomaticRegistration()` call, then in the Xcode console you can see the phrase **"Fetch of items from Google Drive is done."** 

If you uncomment the line `URLSessionProxyDelegate.enableAutomaticRegistration()` in the `viewDidAppear` method of the `ViewController`, then the response from the google service will never be received, and in some scenario it may lead to a deadlock in `GTMSessionFetcher` and the application hangs.

I hope this helps debug and fix a problem in your really interesting and useful library.

P. S. Yes, manual logging of network requests works, but it is not always convenient and informative, because not all modules can connect EventMonitor.

**Comment by kean** [comment]
I added a workaround in version [3.4.3](https://github.com/kean/Pulse/releases/tag/3.4.3) where `URLSessionProxyDelegate.enableAutomaticRegistration` skips `GTMSessionFetcher`. Obviously, it's less than perfect. I'm not sure what else I could do.
