### ISSUE TITLE
Crashes on iOS 14

### ISSUE THREAD

**Issue by ElonPark** [kean/Pulse#171]
Hello! First of all, thank you for your framework! It helps a lot and it is by far the most powerful logging tool.

But unfortunately, I encountered crash using it.

Pulse version: 3.5.3
iOS version: 14.5 iPhone 12 Pro simulators

## 1. `type metadata accessor for AttributedString`
  <img src="https://user-images.githubusercontent.com/13270453/223386684-2c7ae7c4-9076-4815-9598-3ead427b4c39.png" alt="" width="800" border="0" />

 #### This link is work for me https://swiftui-lab.com/bug-os-check/
- But, it's appear compiler warning
  <img width="800" alt="스크린샷 2023-03-07 오후 6 55 06" src="https://user-images.githubusercontent.com/13270453/223387657-16293670-1f70-421d-927f-544d181cb8ad.png">

## 2. CoreData Crash
  <img width="800" alt="스크린샷 2023-03-07 오후 6 45 26" src="https://user-images.githubusercontent.com/13270453/223388437-3fa9430f-9a11-442c-a5a3-9c1e0624d904.png">

**Comment by kean** [comment]
Thanks for providing all these details. I'm able to reproduce the crash, but I'm not sure why it happens. Using #available also leads to a crash. If you integrate the framework itself in the app that supports iOS 14 and run it, it works fine.

**Comment by ElonPark** [comment]
> Thanks for providing all these details. I'm able to reproduce the crash, but I'm not sure why it happens. Using #available also leads to a crash. If you integrate the framework itself in an app that supports iOS 14 and run it, it works fine.

You're right. In fact, there are no issues with the integration in iOS 14.
However, when I run the test on iOS 14, it crashes. I don't know why.

---
On a separate note, the coreData crash in the second bullet point is a real-world case. It happened when I pressed the button shown in the attached screenshot on iOS 14.

<img width="703" alt="스크린샷 2023-03-10 오후 4 00 27" src="https://user-images.githubusercontent.com/13270453/224246182-629415c7-00fb-4536-98f2-9671e034893c.png">

**Comment by kean** [comment]
I fixed the issue with running tests on iOS 14 in the 3.6.0 branch https://github.com/kean/Pulse/pull/177.

I'm able to reproduce the crash but not sure what the root cause is yet.

**Comment by kean** [comment]
I found multiple [reports](https://developer.apple.com/forums/thread/662240) about a Core Data regression in iOS 14 SDK that leads to this crash. I'm looking for ways to address it. But, to be honest, iOS 14 was never well supported because of SwiftUI limitations. I'm considering removing iOS 14 support altogether.

>  It happened when I pressed the button shown in the attached screenshot on iOS 14.

It seems to happen randomly as you are using the app.

**Comment by clarexine** [comment]
Hello and thanks for this great product.

I work with it well until I do some Unit Test with my application.
When I test inside Xcode there is no problem. 
But when using fastlane, xctest crash because of using AttributedString, I think (see crash log).

I precise that in this test my app does not use Pulse but simply "import Pulse" without call any log

[crash.txt](https://github.com/kean/Pulse/files/11101652/crash.txt)

I fix it for now by using the 3.3 version.

Best regard

**Comment by ElonPark** [comment]
@kean The core data crash on iOS 14 is very repetitive for the same reason, and I'm not sure exactly why. 🤔 

![스크린샷 2023-04-18 오후 8 08 27](https://user-images.githubusercontent.com/13270453/232759385-cf79d675-3d46-4e25-bef5-1922be9bcb4c.png)
