### ISSUE TITLE
[Feature Request][Pulse Mac] Automatically scroll down to the bottom when new messages arrive

### ISSUE THREAD

**Issue by hugovanderlei** [kean/Pulse#189]
It would be great if there was a button that we could enable/disable a feature to automatically scrolled down to the bottom whenever a new message arrived.

**Comment by hugovanderlei** [comment]
oh great! thank you!

**Comment by kean** [comment]
Fixed in version 4.0.0 (4).

I had to use `NSTableView` APIs. But I think I'll have to switch from `SwiftUI.Table` to `NSTableView`. The SwiftUI version has performance issues, and I can't implement everything I want, e.g. configurable columns. There will be more improvements in the upcoming release.  

Thanks for testing the app and I appreciate the feedback!

**Comment by hugovanderlei** [comment]
I'm the one who should thank you.
