### ISSUE TITLE
Feature Request - Carthage Support

### ISSUE THREAD

**Issue by sgruby** [kean/Pulse#50]
I'd love to see Carthage support again. I don't use SPM because I like to have all the source inside of my own repo in case something happens to the external dependencies. Up until the latest release, I was just including the PulseCore sources and things worked fine even without Carthage support. The latest release adds the PulseInternal which breaks using just the source because Core relies on Internal and won't compile.

While I can use SPM as a local package, it brings in swift-log.

I understand that SPM is the new fangled way of doing frameworks/libraries, but it doesn't afford me the control I'd like.

I'm probably alone in my request for this and I can make the local SPM work, but it isn't ideal.

**Comment by kean** [comment]
I had a feeling that this change could inadvertently affect something, but didn't expect it to be this quick. I think I can reverse course with PulseInternal - I don't like that change and I don't like having any non-Swift files in it.

I was also thinking about adding Carthage and CocoaPods support, because it's starting to feel like they are not going away any time soon. You are not alone still using Carthage - I also do in some projects and I use precompiled Pulse XCFrameworks in those.

**Comment by kean** [comment]
I've run into some issues with Carthage support. If someone is looking for this option, please consider using XCFrameworks. I'll be attaching pre-compiled XCFrameworks to every release moving forward, starting with [0.19.5](https://github.com/kean/Pulse/releases/tag/0.19.5).

**Comment by sgruby** [comment]
As long I can just just Carthage to bring down the source and drag the source files into my project, I personally don't need anything more than that. In fact, not having a framework is more convenient since I embed the source files in a shared framework for my (internal) projects.

**Comment by kean** [comment]
I'm going to close it because there are no plans to add Carthage support.
